apiVersion: apps/v1
kind: Deployment
metadata:
  name: cacui
spec:
  replicas: 1 # Number of replicas you want to deploy
  selector:
    matchLabels:
      app: cacui
  template:
    metadata:
      labels:
        app: cacui
    spec:
      containers:
        - name: cacui
          image: 599355715474.dkr.ecr.us-east-1.amazonaws.com/demo-ui:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Port that your React app is running on
          env:
            - name: DNS_URL
              value: cacplatformui.com1
            - name: KEYCLOAK_URL
              value: http://keycloak-service.default.svc.cluster.local:8080/auth
            - name: KEYCLOAK_REALM_NAME
              value: keycloak-cac-platform
            - name: KEYCLOAK_CLIENT_ID
              value: react-auth

          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "500m"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: cacui
spec:
  selector:
      app: cacui
  ports:
    - name: http
      port: 8081 # Port that the service should listen on
      targetPort: 3000 # Port that the pods are listening on
  type: LoadBalancer # Use LoadBalancer type if running on cloud providers like AWS, GCP etc
